version: '3.8'

services:
  # Node.js application service
  server:
    image: rohitpatil07/collegemgmt-server
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: server
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
    stdin_open: true 
    tty: true  
    # networks:
    #   - network1

  # MySQL service
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    # networks:
    #   - network1
  client:
    image: rohitpatil07/collegemgmt-client
    container_name: client
    env_file:
      - client.env
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true   
    # networks:
    #  - network1   
# networks:
#   network1:
volumes:
  db_data:
